# Generated by Django 5.1.2 on 2025-10-30 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fashion", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="couponusage",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coupon_usages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fashionreport",
            name="cloth",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="fashion.clothing",
            ),
        ),
        migrations.AddField(
            model_name="fashionreport",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cloth_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fashionreview",
            name="cloth",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fashion_reviews",
                to="fashion.clothing",
            ),
        ),
        migrations.AddField(
            model_name="fashionreview",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fashion_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fashionwishlist",
            name="cloth",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fashion_wishlists",
                to="fashion.clothing",
            ),
        ),
        migrations.AddField(
            model_name="fashionwishlist",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fashion_wishlist",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="couponusage",
            unique_together={("user", "coupon")},
        ),
        migrations.AlterUniqueTogether(
            name="fashionwishlist",
            unique_together={("user", "cloth")},
        ),
    ]
