# Generated by Django 5.1.2 on 2025-11-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_address_latitude_address_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="address_type",
            field=models.CharField(
                choices=[("Home", "Home"), ("Work", "Work"), ("Other", "Other")],
                max_length=20,
                null=True,
            ),
        ),
    ]
