# Generated by Django 5.1.2 on 2025-11-05 17:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliverypartner", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryCharges",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "distance_from",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Starting distance in km",
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "distance_to",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Ending distance in km",
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "day_charge",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Delivery charge during day time",
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "night_charge",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Delivery charge during night time",
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "night_start_time",
                    models.TimeField(
                        default="22:00:00", help_text="Night rate starts from this time"
                    ),
                ),
                (
                    "night_end_time",
                    models.TimeField(
                        default="06:00:00", help_text="Night rate ends at this time"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this charge rule is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Delivery Charge",
                "verbose_name_plural": "Delivery Charges",
                "db_table": "delivery_charges",
                "ordering": ["distance_from"],
            },
        ),
    ]
