# Generated by Django 5.1.2 on 2025-10-30 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("foodproduct", "0001_initial"),
        ("vendors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dishreport",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dish_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dishreview",
            name="dish",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="foodproduct.dish",
            ),
        ),
        migrations.AddField(
            model_name="dishreview",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dish_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="foodcoupon",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="foodcoupons",
                to="vendors.vendor",
            ),
        ),
        migrations.AddField(
            model_name="foodcouponusage",
            name="coupon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Foodcoupon_usages",
                to="foodproduct.foodcoupon",
            ),
        ),
        migrations.AddField(
            model_name="foodcouponusage",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Foodcoupon_usages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="foodsubcategories",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="food_subcategories",
                to="vendors.category",
            ),
        ),
        migrations.AddField(
            model_name="foodsubcategories",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="food_subcategories",
                to="vendors.vendor",
            ),
        ),
        migrations.AddField(
            model_name="vendorbannerfoodproducts",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="highlighted_in_banners",
                to="foodproduct.dish",
            ),
        ),
        migrations.AddField(
            model_name="vendorbannerfoodproducts",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="food_banners",
                to="vendors.vendor",
            ),
        ),
        migrations.AddField(
            model_name="wishlist",
            name="dish",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wishlists",
                to="foodproduct.dish",
            ),
        ),
        migrations.AddField(
            model_name="wishlist",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wishlist",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="foodcouponusage",
            unique_together={("user", "coupon")},
        ),
        migrations.AlterUniqueTogether(
            name="wishlist",
            unique_together={("user", "dish")},
        ),
    ]
