# Generated by Django 5.1.2 on 2025-10-30 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("groceryproducts", "0001_initial"),
        ("vendors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="grocery_wishlist",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grocery",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="grocerycoupon",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grocerycoupons",
                to="vendors.vendor",
            ),
        ),
        migrations.AddField(
            model_name="grocerycouponusage",
            name="coupon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Grocerycoupon_usages",
                to="groceryproducts.grocerycoupon",
            ),
        ),
        migrations.AddField(
            model_name="grocerycouponusage",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Grocerycoupon_usages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="groceryproductreport",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groceryproduct_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="groceryproductreview",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="groceryproducts",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="vendors.category"
            ),
        ),
        migrations.AddField(
            model_name="groceryproducts",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grocery",
                to="vendors.subcategory",
            ),
        ),
        migrations.AddField(
            model_name="groceryproducts",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grocery",
                to="vendors.vendor",
            ),
        ),
        migrations.AddField(
            model_name="groceryproductreview",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="groceryproducts.groceryproducts",
            ),
        ),
        migrations.AddField(
            model_name="groceryproductreport",
            name="grocery_product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="groceryproducts.groceryproducts",
            ),
        ),
        migrations.AddField(
            model_name="groceryproductimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="groceryproducts.groceryproducts",
            ),
        ),
        migrations.AddField(
            model_name="grocery_wishlist",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grocery",
                to="groceryproducts.groceryproducts",
            ),
        ),
        migrations.AddField(
            model_name="grocerysubcategories",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grocery_subcategories",
                to="vendors.category",
            ),
        ),
        migrations.AddField(
            model_name="grocerysubcategories",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grocery_subcategories",
                to="vendors.vendor",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="grocerycouponusage",
            unique_together={("user", "coupon")},
        ),
        migrations.AlterUniqueTogether(
            name="grocery_wishlist",
            unique_together={("user", "product")},
        ),
    ]
