# Generated by Django 5.1.2 on 2025-10-30 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("coupon_tracking", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="usercouponusage",
            name="coupon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usages",
                to="users.coupon",
            ),
        ),
        migrations.AddField(
            model_name="usercouponusage",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_coupon_usages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usercouponusage",
            unique_together={("coupon", "user", "checkout")},
        ),
    ]
