# Generated by Django 5.1.2 on 2025-11-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="otp_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
